name: Build HevSocks5Tunnel

on:
  workflow_dispatch:
  push:
    tags:
      - 'hevsocks5-*'

jobs:
  build-hevsocks5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HevSocks5Tunnel
        uses: actions/checkout@v4
        with:
          repository: 'zloserver/hev-socks5-tunnel'
          ref: 'master'
          path: 'hevsocks5'
          submodules: 'recursive'

      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: 'release'
          path: 'release'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11

      - name: Build HevSocks5Tunnel
        run: |
          cd hevsocks5
          ./build-android.sh

      - name: Copy library to release branch
        run: |
          mvn install:install-file -Dfile=hevsocks5/android/build/outputs/aar/hevsocks5-android-release.aar -DgroupId=com.zloserver.vpn.deps -DartifactId=hevsocks5-android -Dversion=1.0.0 -Dpackaging=aar -DlocalRepositoryPath=release

      - name: Push release branch
        run: |
          cd release
          git config --global user.name "Github Actions"
          git config --global user.email ""
          git add .
          git commit -m "HevSocks5Tunnel update"
          git push
